//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServceTestSup.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tc1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tc1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int num1Field;
        
        private int num2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int num1 {
            get {
                return this.num1Field;
            }
            set {
                if ((this.num1Field.Equals(value) != true)) {
                    this.num1Field = value;
                    this.RaisePropertyChanged("num1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int num2 {
            get {
                return this.num2Field;
            }
            set {
                if ((this.num2Field.Equals(value) != true)) {
                    this.num2Field = value;
                    this.RaisePropertyChanged("num2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServceTestSup.ServiceReference1.HelloWorldResponse HelloWorld(WebServceTestSup.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServceTestSup.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tc1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        WebServceTestSup.ServiceReference1.SubResponse Sub(WebServceTestSup.ServiceReference1.SubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.SubResponse> SubAsync(WebServceTestSup.ServiceReference1.SubRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServceTestSup.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServceTestSup.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServceTestSup.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServceTestSup.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sub", Namespace="http://tempuri.org/", Order=0)]
        public WebServceTestSup.ServiceReference1.SubRequestBody Body;
        
        public SubRequest() {
        }
        
        public SubRequest(WebServceTestSup.ServiceReference1.SubRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServceTestSup.ServiceReference1.Tc1 tc1;
        
        public SubRequestBody() {
        }
        
        public SubRequestBody(WebServceTestSup.ServiceReference1.Tc1 tc1) {
            this.tc1 = tc1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServceTestSup.ServiceReference1.SubResponseBody Body;
        
        public SubResponse() {
        }
        
        public SubResponse(WebServceTestSup.ServiceReference1.SubResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SubResult;
        
        public SubResponseBody() {
        }
        
        public SubResponseBody(int SubResult) {
            this.SubResult = SubResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServceTestSup.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServceTestSup.ServiceReference1.WebService1Soap>, WebServceTestSup.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServceTestSup.ServiceReference1.HelloWorldResponse WebServceTestSup.ServiceReference1.WebService1Soap.HelloWorld(WebServceTestSup.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServceTestSup.ServiceReference1.HelloWorldRequest inValue = new WebServceTestSup.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServceTestSup.ServiceReference1.HelloWorldRequestBody();
            WebServceTestSup.ServiceReference1.HelloWorldResponse retVal = ((WebServceTestSup.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.HelloWorldResponse> WebServceTestSup.ServiceReference1.WebService1Soap.HelloWorldAsync(WebServceTestSup.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServceTestSup.ServiceReference1.HelloWorldRequest inValue = new WebServceTestSup.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServceTestSup.ServiceReference1.HelloWorldRequestBody();
            return ((WebServceTestSup.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServceTestSup.ServiceReference1.SubResponse WebServceTestSup.ServiceReference1.WebService1Soap.Sub(WebServceTestSup.ServiceReference1.SubRequest request) {
            return base.Channel.Sub(request);
        }
        
        public int Sub(WebServceTestSup.ServiceReference1.Tc1 tc1) {
            WebServceTestSup.ServiceReference1.SubRequest inValue = new WebServceTestSup.ServiceReference1.SubRequest();
            inValue.Body = new WebServceTestSup.ServiceReference1.SubRequestBody();
            inValue.Body.tc1 = tc1;
            WebServceTestSup.ServiceReference1.SubResponse retVal = ((WebServceTestSup.ServiceReference1.WebService1Soap)(this)).Sub(inValue);
            return retVal.Body.SubResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.SubResponse> WebServceTestSup.ServiceReference1.WebService1Soap.SubAsync(WebServceTestSup.ServiceReference1.SubRequest request) {
            return base.Channel.SubAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServceTestSup.ServiceReference1.SubResponse> SubAsync(WebServceTestSup.ServiceReference1.Tc1 tc1) {
            WebServceTestSup.ServiceReference1.SubRequest inValue = new WebServceTestSup.ServiceReference1.SubRequest();
            inValue.Body = new WebServceTestSup.ServiceReference1.SubRequestBody();
            inValue.Body.tc1 = tc1;
            return ((WebServceTestSup.ServiceReference1.WebService1Soap)(this)).SubAsync(inValue);
        }
    }
}
